# **Theoretical Questions:**

Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Sol. Purpose of Numpy:-


1.   Efficient Numerical Computations:- NumPy is designed to handle large amounts of numerical data efficiently. It provides powerful tools to work with arrays and enabling complex operations.

2.  Array Creation:- NumPy helps create multi-dimensional arrays and process arrays that store values of the same data type

3.  Foundation for Other Libraries:- NumPy serves as the foundation for many other scientific libraries in Python, such as Pandas etc.

4.  Interfacing with C, C++, and Fortran:- NumPy arrays can be easily passed to other languages like C, C++, and Fortran.


Advantages of Numpy in Scientific Computing and Data analysis:-



1.   Performance:- NumPy's array operations are faster than Python lists because they are executed at compiled C speed. This is important for handling large datasets and complex computations.

2.   Memory efficiency:- NumPy arrays use contiguous memory blocks, which reduces overhead compared to Python lists. This is important for dealing with extensive datasets

3.   Mathematical functions:- NumPy provides a rich collection of mathematical functions, including basic arithmetic operations, statistical functions, linear algebra operations, and Fourier transforms.

4.  Vectorized Operations:- One of the biggest advantages of NumPy is its ability to perform vectorized operations. This means that instead of writing loops to operate on each element of an array individually, you can apply operations directly to the entire array.


5.  Indexing and Slicing:- NumPy supports advanced indexing, slicing, and reshaping techniques for its arrays, which makes data manipulation fast and efficient.

6.   Broadcasting:- NumPy's broadcasting capability allows for arithmetic operations between arrays of different shapes and sizes

7.   Integration:-NumPy integrates with other libraries and tools in the scientific Python ecosystem, such as SciPy, Pandas, Matplotlib, and scikit-learn.



---



---



Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Sol. Comparison of np.mean() and np.average() in different aspects:-

1. Basic Function:-

  *   np.mean():- Computes the arithematic mean of elements in an array.
  *   np.average():- Computes the average of elements in an array with different weights and if weight is not assigned then it simply calculates the mean.

2. Supports of Weights:-

  *   In np.mean() there is no support of weights.
  *   np.average() supports weights in calculations.

3. Result:-

  *   np.mean() gives the mean of elements in an array.
  *   np.average() gives the average with different weights and if no weight is assigned then it calculates the mean.

4. Performance:-

  *   np.mean() is slight;y faster.
  *   np.average() is slower due to weight handeling.

5. Use case:-

  *   np.mean() is used when equal importance is given to all the elements.
  *   np.average() is used when elements have different importance.







---



---



Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Sol. Reversing of Numpy array along different axis in pyhton can be done by 2 different methods:-

1. Slicing:- With the help of slicing we can reverse an array along its axis by simply using  (array[start:stop:step]) where step =-1.

2. Using flip() method:- Another way of reversing an array along its axis is to use flip method. which is used as (np.flip(array_name,axis)) here we can pass (0 or 1) in axis according to the axis we have to flip or pass both to flip the whole array

Example:-

In [ ]:
## Raversing using slicing:-

import numpy as np

arr=np.array([1,2,3,4,5])
print("Reverse of 1-d array: ")
print(arr[::-1])

arr1=np.array([[1,2,3],[4,5,6]])
print("Reverse of 2-d array along x-axis: ")
print(arr1[::-1,])
print("Reverse of 2-d array along y-axis: ")
print(arr1[:,::-1])


print("Reverse of 2-d array along both the axis: ")
print(arr1[::-1,::-1])

Reverse of 1-d array: 
[5 4 3 2 1]
Reverse of 2-d array along x-axis: 
[[4 5 6]
 [1 2 3]]
Reverse of 2-d array along y-axis: 
[[3 2 1]
 [6 5 4]]
Reverse of 2-d array along both the axis: 
[[6 5 4]
 [3 2 1]]


In [ ]:
## Raversing using flip method:-

import numpy as np

arr=np.array([1,2,3,4,5])
print("Reverse of 1-d array: ")
print(np.flip(arr))

arr1=np.array([[1,2,3],[4,5,6]])
print("Reverse of 2-d array along x-axis: ")
print(np.flip(arr1,axis=0))
print("Reverse of 2-d array along y-axis: ")
print(np.flip(arr1,axis=1))


print("Reverse of 2-d array along both the axis: ")
print(np.flip(arr1,axis=(0,1)))

Reverse of 1-d array: 
[5 4 3 2 1]
Reverse of 2-d array along x-axis: 
[[4 5 6]
 [1 2 3]]
Reverse of 2-d array along y-axis: 
[[3 2 1]
 [6 5 4]]
Reverse of 2-d array along both the axis: 
[[6 5 4]
 [3 2 1]]




---



---



Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Sol. Using dtype we can determine the datatype of an array, with the help of dtype we can also assign the datatype to an array at the time of its creation.

Importance of datatype in memory management and performance:-

1. Memory Management:- Different datatypes are of different sizes and occupy different space in the memory.If an array is created of a particular datatype of higher space requirement then the array will occupy more memory than others.

2. Performance:- Data types also impact the performance of numerical operations. Smaller data types can lead to faster computations because they require fewer bits to process. However, they may sacrifice precision, so you need to balance between memory efficiency and the precision required for your application.





---



---



Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Sol. ndarrays in numpy is an array of homogenous elements of n-dimensions,which means with the help of numpy we can create an array of any dimensions with ease.  

Key features of ndarrays:-

1. Homogenous Datatype:- All elements of ndarray are of same datatype.

2.  Performance:- NumPy's array operations are faster than Python lists because they are executed at compiled C speed. This is important for handling large datasets and complex computations.

3.   Memory efficiency:- NumPy arrays use contiguous memory blocks, which reduces overhead compared to Python lists. This is important for dealing with extensive datasets

4.  Mathematical functions:- NumPy provides a rich collection of mathematical functions, including basic arithmetic operations, statistical functions, linear algebra operations, and Fourier transforms.

5.  Vectorized Operations:- One of the biggest advantages of NumPy is its ability to perform vectorized operations. This means that instead of writing loops to operate on each element of an array individually, you can apply operations directly to the entire array.

6.  Indexing and Slicing:- NumPy supports advanced indexing, slicing, and reshaping techniques for its arrays, which makes data manipulation fast and efficient.

7.  Broadcasting:- NumPy's broadcasting capability allows for arithmetic operations between arrays of different shapes and sizes

8.  Integration:-NumPy integrates with other libraries and tools in the scientific Python ecosystem, such as SciPy, Pandas, Matplotlib, and scikit-learn.

Difference between ndarrays and lists:-

1. Datatype:- ndarrays are of homogenous datatype where as lists is collection of elements of hetrogenous datatypes.

2. Memory Efficiency:- ndarrays are more efficient than lists.

3. Broadcasting:- Broadcasting is possible in ndarrays but not in lists.

4. Performance:- ndarrays provides optimized performance for numerical operations list are slower as compared to arrays.

5. Vectorized Operations:- It is possible in ndarrays but not in lists.




---



---



Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Sol. Performance benefits of Numpy arrays over lists are:-

1. Memory Management:- Numpy arrays are more momery efficient than lists because its stores its elements in contiguous memory locations, and the other reason behing it is numpy arrays are collection of elements of same data types.

2. Performance:- Numpy arrays are faster than lists because, the arrays are stored in contiguous memory locations which makes it faster as it is more efficent to confiure an operation in a continuous memory address rather than different memory spaces.

3. Vectorized Operations:- One of the biggest advantages of NumPy is its ability to perform vectorized operations. This means that instead of writing loops to operate on each element of an array individually, you can apply operations directly to the entire array.

4. Broadcasting:- NumPy's broadcasting capability allows for arithmetic operations between arrays of different shapes and sizes

5. Mathematical Functions:- Numpy arrays has faster C-based mathematical functions whereas lists has slower python-based functions.



---



---



Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Sol. vstack():- used to stack two or more arrays vertically.

hstack():- used to stack two or more arrays horizontally.

Example:-

In [ ]:
# Vertical stacking of arrays

import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
print("Verticak Stack : ")
print(np.vstack((a,b)))

# Hortizontal stacking of array

print("Horizontal Stack : ")
print(np.hstack((a,b)))

Verticak Stack : 
[[1 2 3]
 [4 5 6]]
Horizontal Stack : 
[1 2 3 4 5 6]




---



---



Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Sol.

1. fliplr():- flips the array in the left to right direction,reversing the order of columns.

  *   It does not work for !-D array
  *   For 2-d array or more the shape of array remains same, only the columns are reversed.

2. flipud():- flips the array in up to down direction, reversing the order of rows without affectinf the order of columns.


*   It works for all the dimensions.
*   like fliplr() it does not change the shape of array just changes the order of columns.

Examole:-



In [8]:
import numpy as np

arr=np.array([1,2,3])
arr1=np.array([[1,2,3],[4,5,6]])

print("fliplr of 2-d array :")
print(np.fliplr(arr1))

print("flipud of 1-d array :")
print(np.flipud(arr))

print("fliplr of 2-d array :")
print(np.flipud(arr1))

fliplr of 2-d array :
[[3 2 1]
 [6 5 4]]
flipud of 1-d array :
[3 2 1]
fliplr of 2-d array :
[[4 5 6]
 [1 2 3]]




---



---



Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Sol.  Splitting divides an array into multiple sub-arrays along a specified axis

For Example:-


In [15]:
import numpy as np

arr3 = np.array([[1, 2], [3, 4], [5, 6]])

print("Splitting across x-axis :")
print(np.split(arr1,2,axis=0))

print("Splitting across y-axis :")
print(np.split(arr3,2,axis=1))

Splitting across x-axis :
[array([[1, 2, 3]]), array([[4, 5, 6]])]
Splitting across y-axis :
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


Handeling Uneven Cases:-

If the array size is not divisible by the number of splits, array_split() ensures that the sub-arrays are as evenly sized as possible. The first sub-arrays will have one extra element compared to the last sub-arrays.

For Example:-

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
np.array_split(arr, 3)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]



---



---



Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Sol. Vectorization:-

NumPy vectorization involves performing mathematical operations on entire arrays, eliminating the need to loop through individual elements.

Example:-

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5 ])
n = 10

print(arr+n)

[11 12 13 14 15]


Broadcating:-
In NumPy, broadcasting is a process that allows for arithmetic operations to be performed on arrays with different shapes:

How it works:-Broadcasting "stretches" or "replicates" smaller arrays to match the dimensions of larger arrays. This eliminates the need to manually reshape arrays or write loops.

Examples:- Broadcasting can be used for per-element arithmetic, multiplying an n-dimensional array by a scalar, dividing a matrix by a vector, and converting a color image to grayscale

In [18]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

print(arr1+arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


Advantages of Vectorization and Broadcasting are:-


1.   Consice Code:- Eleminates the need of loops
2.   Fast Execution:- Operations are performed in C
3.   Low memory needed:- Broadcasting avoids unnecessary memory duplication,keeping operations memory efficient.





---



---



# **Practical Questions:**

Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

arr=np.randomm.randint(1,100,(3,3))

print(a)



---



---



Q2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np

arr=np.random.rand(10)
print(arr.reshape(2,5))
print("")
print(arr.reshape(5,2))

[[0.58923703 0.03135065 0.72337071 0.61564135 0.29767931]
 [0.7467137  0.45705328 0.86723485 0.31762999 0.50299293]]

[[0.58923703 0.03135065]
 [0.72337071 0.61564135]
 [0.29767931 0.7467137 ]
 [0.45705328 0.86723485]
 [0.31762999 0.50299293]]




---



---



Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
import numpy as np

arr1=np.random.rand(4,4)
print(arr)
print("\n")
print(np.pad(arr1,pad_width=1, mode='constant', constant_values=0))

['python' 'numpy' 'pandas']


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.57892188 0.18547648 0.49334768 0.9685985  0.        ]
 [0.         0.21871728 0.4434093  0.41201853 0.81821084 0.        ]
 [0.         0.73549872 0.29995349 0.36801036 0.26200351 0.        ]
 [0.         0.5500597  0.77500359 0.97663324 0.27027082 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]




---



---



Q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np

arr=np.arange(10,61,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])



---



---



Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [ ]:
import numpy as np

s=['python', 'numpy', 'pandas']

arr=np.array(s)
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']




---



---



Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [2]:
import numpy as np

s=["pwskills",'hello',"world"]

arr=np.array([" ".join(i) for i in s])

arr

array(['p w s k i l l s', 'h e l l o', 'w o r l d'], dtype='<U15')



---



---



Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

print(arr1)
print("\n")
print(arr2)

print("Addition : ")
print(arr1+arr2)
print("\n")

print("Subtraction : ")
print(arr1-arr2)
print("\n")

print("Multiplication : ")
print(arr1*arr2)
print("\n")

print("Division : ")
print(arr1//arr2)
print("\n")

[[2 5 8]
 [4 2 2]
 [8 9 6]]


[[6 1 7]
 [2 5 1]
 [7 2 4]]
Addition : 
[[ 8  6 15]
 [ 6  7  3]
 [15 11 10]]


Subtraction : 
[[-4  4  1]
 [ 2 -3  1]
 [ 1  7  2]]


Multiplication : 
[[12  5 56]
 [ 8 10  2]
 [56 18 24]]


Division : 
[[0 5 1]
 [2 0 2]
 [1 4 1]]






---



---



Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [4]:
import numpy as np

arr=np.eye(5)
print(arr)
print("\n")
print(np.diag(arr))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[1. 1. 1. 1. 1.]




---



---



Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.


In [5]:
import numpy as np

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

arr = np.random.randint(0, 1000, size=100)
arr1 = np.array([i for i in arr if is_prime(i)])

arr1

array([167,  19, 509,  37, 463, 227, 647, 487, 443, 313, 983, 617, 947,
       673,  23, 421, 719, 281,  83, 337, 751])



---



---



Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [7]:
import numpy as np

t=np.random.randint(20,30,size=28)
print(t)
print("\n")

week=t.reshape(4,7)

week_mean=np.mean(week,axis=1)
print(week_mean)

[26 29 20 23 27 28 24 23 25 29 25 27 22 26 25 22 27 23 28 22 23 22 25 22
 26 20 28 26]


[25.28571429 25.28571429 24.28571429 24.14285714]
